### ISSUE TITLE
feat: Issuer Dashboard

### ISSUE THREAD

**Issue by PaddyMc** [elesto-dao/elesto#109]
The issuer dashboard is a frontend application that acts as a controller for an Aries cloud agent.

The issuer dashboard will:

- Create invitations
- Issue credentials
- Send messages

Design:
https://whimsical.com/elesto-issuer-dashboard-QwJvnvs7WERcUauDREkLoM

GitHub:
https://github.com/elesto-dao/elesto-issuer-dashboard

Success criteria:
- [ ] initial wireframes and design document
- [ ] issuer dashboard can communicate effectively with an Aries cloud agent
- [ ] issuer dashboard is deployed on testnet and used by CNS

**Comment by hpsing** [comment]
Issuer dashboard development is in [Issuer-dashboard repo](https://github.com/elesto-dao/elesto-issuer-dashboard). Please use this repo.
