### ISSUE TITLE
Finalize node code for release candidate 2 v1

### ISSUE THREAD

**Issue by PaddyMc** [elesto-dao/elesto#42]
### Description
This task contains the last tasks left to cut a v1.0.0-rc2

### Code additions
- [x] Integrate store migrations 
- [x] [Remove TODOs detailed here](https://github.com/elesto-dao/elesto/blob/main/x/did/did_verification_material.go#L104)
- [x] [Core team audit](https://www.notion.so/allinbits/Elesto-37a9ec66fc4042d8a225193fd23d3787)  :heart: 
- [x] [Invariance Checks](https://app.zenhub.com/workspaces/elesto-61fab4ab4ee6550016ebddd9/issues/elesto-dao/elesto/51)
- [x] [Import/export script](https://app.zenhub.com/workspaces/elesto-61fab4ab4ee6550016ebddd9/issues/elesto-dao/elesto/52)

### Documentation
- [x] GoDoc comments on all code
    - [x] keeper package
    - [x] did package
    - [x] proto files

### Testing and sims
- [x] Update DID script to test updating a did
- [x] Final review unit and integration tests
- [x] Final review elesto code base

- [x] Simulations for: e.g [example](https://github.com/osmosis-labs/osmosis/blob/main/sims.mk)
    - [x] nondeterminism => Running non-determinism test
    - [x] import/export => Running application import/export simulation
    - [x] etc....

### Dependencies 
~- [ ] Update cosmos-sdk to v0.46.0 (when it;s released)~
- [x] Update all packages to latest version (ibc-go!!!)
- [x] add authz and groups modules
- [x] Prepare package analysis

**Comment by PaddyMc** [comment]
group module is v0.46.x release series, and 0.46.x is not released

lets cut rc-2 from now :tada:
