### ISSUE TITLE
Final review of code and tag v1.0.0-rc2

### ISSUE THREAD

**Issue by PaddyMc** [elesto-dao/elesto#67]
### Description

- this is the final release of the codebase before go-live
- this is the tag && branch that should be released

### Tasks

- [x] add changelog config
- [ ]  simplify the release process
- [x]  update CODEOWNERS
- [x]  review code
- [x]  create branch and tag release
- [ ]  create tag description for v1.0.0
- [x]  announce code freeze
